"""initial_schema

Revision ID: 8e9091b03d62
Revises: 
Create Date: 2026-03-28 04:25:00.573848
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



# revision identifiers, used by Alembic.
revision = '8e9091b03d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_tool_profile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_role_templates_key')
    )
    op.create_index(op.f('ix_role_templates_id'), 'role_templates', ['id'], unique=False)
    op.create_index(op.f('ix_role_templates_key'), 'role_templates', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firebase_uid', name='uq_users_firebase_uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('github_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', name='uq_github_connections_installation_id')
    )
    op.create_index(op.f('ix_github_connections_id'), 'github_connections', ['id'], unique=False)
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shared_workspace_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_mode'), 'teams', ['mode'], unique=False)
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('role_template_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('runtime_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hermes_home_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('private_volume_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shared_workspace_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_role_template_id'), 'agents', ['role_template_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_team_id'), 'agents', ['team_id'], unique=False)
    op.create_table('shared_workspace_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_workspace_items_id'), 'shared_workspace_items', ['id'], unique=False)
    op.create_index(op.f('ix_shared_workspace_items_kind'), 'shared_workspace_items', ['kind'], unique=False)
    op.create_index(op.f('ix_shared_workspace_items_team_id'), 'shared_workspace_items', ['team_id'], unique=False)
    op.create_table('automation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_jobs_agent_id'), 'automation_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_id'), 'automation_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_team_id'), 'automation_jobs', ['team_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latest_response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_mode'), 'conversations', ['mode'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_team_id'), 'conversations', ['team_id'], unique=False)
    op.create_table('runtime_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('vm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='uq_runtime_leases_agent_id')
    )
    op.create_index(op.f('ix_runtime_leases_agent_id'), 'runtime_leases', ['agent_id'], unique=False)
    op.create_index('ix_runtime_leases_agent_id_state', 'runtime_leases', ['agent_id', 'state'], unique=False)
    op.create_index(op.f('ix_runtime_leases_id'), 'runtime_leases', ['id'], unique=False)
    op.create_index(op.f('ix_runtime_leases_state'), 'runtime_leases', ['state'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secrets_agent_id'), 'secrets', ['agent_id'], unique=False)
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_index(op.f('ix_secrets_scope'), 'secrets', ['scope'], unique=False)
    op.create_index(op.f('ix_secrets_team_id'), 'secrets', ['team_id'], unique=False)
    op.create_index(op.f('ix_secrets_user_id'), 'secrets', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preview_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_agent_id'), 'artifacts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_artifacts_conversation_id'), 'artifacts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_artifacts_team_id'), 'artifacts', ['team_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_actor_id'), 'messages', ['actor_id'], unique=False)
    op.create_index(op.f('ix_messages_actor_type'), 'messages', ['actor_type'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_response_chain_id'), 'messages', ['response_chain_id'], unique=False)
    op.create_table('tool_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_events_agent_id'), 'tool_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_events_conversation_id'), 'tool_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_events_event_type'), 'tool_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tool_events_id'), 'tool_events', ['id'], unique=False)
    op.create_index(op.f('ix_tool_events_message_id'), 'tool_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_tool_events_tool_name'), 'tool_events', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_events_tool_name'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_message_id'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_id'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_event_type'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_conversation_id'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_agent_id'), table_name='tool_events')
    op.drop_table('tool_events')
    op.drop_index(op.f('ix_messages_response_chain_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_actor_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_actor_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_artifacts_team_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_conversation_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_agent_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_secrets_user_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_team_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_scope'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_agent_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_runtime_leases_state'), table_name='runtime_leases')
    op.drop_index(op.f('ix_runtime_leases_id'), table_name='runtime_leases')
    op.drop_index('ix_runtime_leases_agent_id_state', table_name='runtime_leases')
    op.drop_index(op.f('ix_runtime_leases_agent_id'), table_name='runtime_leases')
    op.drop_table('runtime_leases')
    op.drop_index(op.f('ix_conversations_team_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_mode'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_automation_jobs_team_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_agent_id'), table_name='automation_jobs')
    op.drop_table('automation_jobs')
    op.drop_index(op.f('ix_shared_workspace_items_team_id'), table_name='shared_workspace_items')
    op.drop_index(op.f('ix_shared_workspace_items_kind'), table_name='shared_workspace_items')
    op.drop_index(op.f('ix_shared_workspace_items_id'), table_name='shared_workspace_items')
    op.drop_table('shared_workspace_items')
    op.drop_index(op.f('ix_agents_team_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_role_template_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_mode'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_index(op.f('ix_github_connections_id'), table_name='github_connections')
    op.drop_table('github_connections')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_templates_key'), table_name='role_templates')
    op.drop_index(op.f('ix_role_templates_id'), table_name='role_templates')
    op.drop_table('role_templates')
    # ### end Alembic commands ###
