"""baseline schema

Revision ID: dcda719dda1c
Revises: 
Create Date: 2026-04-03 03:38:03.001569
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401



# revision identifiers, used by Alembic.
revision = 'dcda719dda1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poller_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sa.Enum('idle', 'running', name='pollerleasestate', native_enum=False), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sweep_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_sweep_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_executed_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poller_leases')),
    sa.UniqueConstraint('name', name='uq_poller_leases_name')
    )
    op.create_index(op.f('ix_poller_leases_id'), 'poller_leases', ['id'], unique=False)
    op.create_index(op.f('ix_poller_leases_name'), 'poller_leases', ['name'], unique=False)
    op.create_index(op.f('ix_poller_leases_owner_id'), 'poller_leases', ['owner_id'], unique=False)
    op.create_index(op.f('ix_poller_leases_state'), 'poller_leases', ['state'], unique=False)
    op.create_table('role_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_tool_profile', sa.Enum('full_web', name='toolprofile', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_templates')),
    sa.UniqueConstraint('key', name='uq_role_templates_key')
    )
    op.create_index(op.f('ix_role_templates_id'), 'role_templates', ['id'], unique=False)
    op.create_index(op.f('ix_role_templates_key'), 'role_templates', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('firebase_uid', name='uq_users_firebase_uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_template_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('provisioning', 'ready', 'running', 'runtime_unreachable', name='agentstatus', native_enum=False), nullable=False),
    sa.Column('runtime_kind', sa.Enum('firecracker', name='runtimekind', native_enum=False), nullable=False),
    sa.Column('hermes_home_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('private_volume_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['role_template_id'], ['role_templates.id'], name=op.f('fk_agents_role_template_id_role_templates')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_role_template_id'), 'agents', ['role_template_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('github_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('installation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sa.Enum('user', 'organization', name='githubaccounttype', native_enum=False), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_github_connections_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_github_connections')),
    sa.UniqueConstraint('installation_id', name='uq_github_connections_installation_id')
    )
    op.create_index(op.f('ix_github_connections_id'), 'github_connections', ['id'], unique=False)
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mode', sa.Enum('personal', 'team', name='teammode', native_enum=False), nullable=False),
    sa.Column('shared_workspace_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teams_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_mode'), 'teams', ['mode'], unique=False)
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    op.create_table('agent_team_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('agent_team_id', sa.Uuid(), nullable=False),
    sa.Column('shared_workspace_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_team_assignments_agent_id_agents')),
    sa.ForeignKeyConstraint(['agent_team_id'], ['teams.id'], name=op.f('fk_agent_team_assignments_agent_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_team_assignments')),
    sa.UniqueConstraint('agent_id', 'agent_team_id', name='uq_agent_team_assignments_agent_team')
    )
    op.create_index(op.f('ix_agent_team_assignments_agent_id'), 'agent_team_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_team_assignments_agent_team_id'), 'agent_team_assignments', ['agent_team_id'], unique=False)
    op.create_index(op.f('ix_agent_team_assignments_id'), 'agent_team_assignments', ['id'], unique=False)
    op.create_table('automation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('agent_team_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_automation_jobs_agent_id_agents')),
    sa.ForeignKeyConstraint(['agent_team_id'], ['teams.id'], name=op.f('fk_automation_jobs_agent_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_jobs'))
    )
    op.create_index(op.f('ix_automation_jobs_agent_id'), 'automation_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_agent_team_id'), 'automation_jobs', ['agent_team_id'], unique=False)
    op.create_index(op.f('ix_automation_jobs_id'), 'automation_jobs', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_team_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.Enum('agent', 'team', 'team_huddle', 'team_member', name='conversationmode', native_enum=False), nullable=False),
    sa.Column('latest_response_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', name='conversationstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_conversations_agent_id_agents')),
    sa.ForeignKeyConstraint(['agent_team_id'], ['teams.id'], name=op.f('fk_conversations_agent_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_agent_team_id'), 'conversations', ['agent_team_id'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_mode'), 'conversations', ['mode'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('runtime_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('vm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host_vm_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('host_api_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sa.Enum('provisioning', 'running', 'unreachable', name='runtimeleasestate', native_enum=False), nullable=False),
    sa.Column('api_base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_runtime_leases_agent_id_agents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_leases')),
    sa.UniqueConstraint('agent_id', name='uq_runtime_leases_agent_id')
    )
    op.create_index(op.f('ix_runtime_leases_agent_id'), 'runtime_leases', ['agent_id'], unique=False)
    op.create_index('ix_runtime_leases_agent_id_state', 'runtime_leases', ['agent_id', 'state'], unique=False)
    op.create_index(op.f('ix_runtime_leases_host_vm_id'), 'runtime_leases', ['host_vm_id'], unique=False)
    op.create_index(op.f('ix_runtime_leases_id'), 'runtime_leases', ['id'], unique=False)
    op.create_index(op.f('ix_runtime_leases_state'), 'runtime_leases', ['state'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sa.Enum('user', 'team', 'agent', name='secretscope', native_enum=False), nullable=False),
    sa.Column('encrypted_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_secrets_agent_id_agents')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_secrets_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_secrets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets'))
    )
    op.create_index(op.f('ix_secrets_agent_id'), 'secrets', ['agent_id'], unique=False)
    op.create_index(op.f('ix_secrets_id'), 'secrets', ['id'], unique=False)
    op.create_index(op.f('ix_secrets_scope'), 'secrets', ['scope'], unique=False)
    op.create_index(op.f('ix_secrets_team_id'), 'secrets', ['team_id'], unique=False)
    op.create_index(op.f('ix_secrets_user_id'), 'secrets', ['user_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('document', 'github_export', name='artifactkind', native_enum=False), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preview_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_artifacts_agent_id_agents')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_artifacts_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_artifacts_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_agent_id'), 'artifacts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_artifacts_conversation_id'), 'artifacts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_artifacts_id'), 'artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_artifacts_team_id'), 'artifacts', ['team_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'assistant', 'system', name='messageactortype', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_chain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_actor_id'), 'messages', ['actor_id'], unique=False)
    op.create_index(op.f('ix_messages_actor_type'), 'messages', ['actor_type'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_response_chain_id'), 'messages', ['response_chain_id'], unique=False)
    op.create_table('shared_workspace_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('file', 'directory', name='workspaceitemkind', native_enum=False), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_shared_workspace_items_agent_id_agents')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_shared_workspace_items_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_shared_workspace_items_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_workspace_items'))
    )
    op.create_index(op.f('ix_shared_workspace_items_agent_id'), 'shared_workspace_items', ['agent_id'], unique=False)
    op.create_index(op.f('ix_shared_workspace_items_conversation_id'), 'shared_workspace_items', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shared_workspace_items_id'), 'shared_workspace_items', ['id'], unique=False)
    op.create_index(op.f('ix_shared_workspace_items_kind'), 'shared_workspace_items', ['kind'], unique=False)
    op.create_index(op.f('ix_shared_workspace_items_team_id'), 'shared_workspace_items', ['team_id'], unique=False)
    op.create_table('team_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_agent_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'claimed', 'completed', name='teamtaskstatus', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('huddle', name='teamtasksource', native_enum=False), nullable=False),
    sa.Column('claim_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], name=op.f('fk_team_tasks_assigned_agent_id_agents')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_team_tasks_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_tasks_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_tasks'))
    )
    op.create_index(op.f('ix_team_tasks_assigned_agent_id'), 'team_tasks', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_team_tasks_claim_expires_at'), 'team_tasks', ['claim_expires_at'], unique=False)
    op.create_index(op.f('ix_team_tasks_claim_token'), 'team_tasks', ['claim_token'], unique=False)
    op.create_index(op.f('ix_team_tasks_conversation_id'), 'team_tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_team_tasks_id'), 'team_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_team_tasks_source'), 'team_tasks', ['source'], unique=False)
    op.create_index(op.f('ix_team_tasks_status'), 'team_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_team_tasks_team_id'), 'team_tasks', ['team_id'], unique=False)
    op.create_table('team_task_updates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('reported', 'message', 'completed', 'delegated', 'claimed', 'released', 'reopened', name='teamtaskupdatetype', native_enum=False), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_team_task_updates_agent_id_agents')),
    sa.ForeignKeyConstraint(['task_id'], ['team_tasks.id'], name=op.f('fk_team_task_updates_task_id_team_tasks')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_task_updates_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_task_updates'))
    )
    op.create_index(op.f('ix_team_task_updates_agent_id'), 'team_task_updates', ['agent_id'], unique=False)
    op.create_index(op.f('ix_team_task_updates_event_type'), 'team_task_updates', ['event_type'], unique=False)
    op.create_index(op.f('ix_team_task_updates_id'), 'team_task_updates', ['id'], unique=False)
    op.create_index(op.f('ix_team_task_updates_task_id'), 'team_task_updates', ['task_id'], unique=False)
    op.create_index(op.f('ix_team_task_updates_team_id'), 'team_task_updates', ['team_id'], unique=False)
    op.create_table('tool_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sa.Enum('started', 'completed', 'failed', name='tooleventtype', native_enum=False), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_tool_events_agent_id_agents')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_tool_events_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_tool_events_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_events'))
    )
    op.create_index(op.f('ix_tool_events_agent_id'), 'tool_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_events_conversation_id'), 'tool_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_events_event_type'), 'tool_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tool_events_id'), 'tool_events', ['id'], unique=False)
    op.create_index(op.f('ix_tool_events_message_id'), 'tool_events', ['message_id'], unique=False)
    op.create_index(op.f('ix_tool_events_tool_name'), 'tool_events', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_events_tool_name'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_message_id'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_id'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_event_type'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_conversation_id'), table_name='tool_events')
    op.drop_index(op.f('ix_tool_events_agent_id'), table_name='tool_events')
    op.drop_table('tool_events')
    op.drop_index(op.f('ix_team_task_updates_team_id'), table_name='team_task_updates')
    op.drop_index(op.f('ix_team_task_updates_task_id'), table_name='team_task_updates')
    op.drop_index(op.f('ix_team_task_updates_id'), table_name='team_task_updates')
    op.drop_index(op.f('ix_team_task_updates_event_type'), table_name='team_task_updates')
    op.drop_index(op.f('ix_team_task_updates_agent_id'), table_name='team_task_updates')
    op.drop_table('team_task_updates')
    op.drop_index(op.f('ix_team_tasks_team_id'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_status'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_source'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_id'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_conversation_id'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_claim_token'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_claim_expires_at'), table_name='team_tasks')
    op.drop_index(op.f('ix_team_tasks_assigned_agent_id'), table_name='team_tasks')
    op.drop_table('team_tasks')
    op.drop_index(op.f('ix_shared_workspace_items_team_id'), table_name='shared_workspace_items')
    op.drop_index(op.f('ix_shared_workspace_items_kind'), table_name='shared_workspace_items')
    op.drop_index(op.f('ix_shared_workspace_items_id'), table_name='shared_workspace_items')
    op.drop_index(op.f('ix_shared_workspace_items_conversation_id'), table_name='shared_workspace_items')
    op.drop_index(op.f('ix_shared_workspace_items_agent_id'), table_name='shared_workspace_items')
    op.drop_table('shared_workspace_items')
    op.drop_index(op.f('ix_messages_response_chain_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_actor_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_actor_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_artifacts_team_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_conversation_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_agent_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_secrets_user_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_team_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_scope'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_agent_id'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_runtime_leases_state'), table_name='runtime_leases')
    op.drop_index(op.f('ix_runtime_leases_id'), table_name='runtime_leases')
    op.drop_index(op.f('ix_runtime_leases_host_vm_id'), table_name='runtime_leases')
    op.drop_index('ix_runtime_leases_agent_id_state', table_name='runtime_leases')
    op.drop_index(op.f('ix_runtime_leases_agent_id'), table_name='runtime_leases')
    op.drop_table('runtime_leases')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_mode'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_team_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_automation_jobs_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_agent_team_id'), table_name='automation_jobs')
    op.drop_index(op.f('ix_automation_jobs_agent_id'), table_name='automation_jobs')
    op.drop_table('automation_jobs')
    op.drop_index(op.f('ix_agent_team_assignments_id'), table_name='agent_team_assignments')
    op.drop_index(op.f('ix_agent_team_assignments_agent_team_id'), table_name='agent_team_assignments')
    op.drop_index(op.f('ix_agent_team_assignments_agent_id'), table_name='agent_team_assignments')
    op.drop_table('agent_team_assignments')
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_mode'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_index(op.f('ix_github_connections_id'), table_name='github_connections')
    op.drop_table('github_connections')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_role_template_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_templates_key'), table_name='role_templates')
    op.drop_index(op.f('ix_role_templates_id'), table_name='role_templates')
    op.drop_table('role_templates')
    op.drop_index(op.f('ix_poller_leases_state'), table_name='poller_leases')
    op.drop_index(op.f('ix_poller_leases_owner_id'), table_name='poller_leases')
    op.drop_index(op.f('ix_poller_leases_name'), table_name='poller_leases')
    op.drop_index(op.f('ix_poller_leases_id'), table_name='poller_leases')
    op.drop_table('poller_leases')
    # ### end Alembic commands ###
